# Generated by Django 3.1.7 on 2021-03-06 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LapakModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lapak_name', models.CharField(max_length=100)),
                ('lapak_type', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('active', models.BooleanField(default=1)),
                ('valid', models.BooleanField(default=0)),
                ('socmed_link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
