# Generated by Django 3.1.7 on 2021-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapakmodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lapakmodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
