# Generated by Django 3.1.7 on 2021-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapakmodel',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lapakmodel',
            name='lapak_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lapakmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lapakmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lapakmodel',
            name='socmed_link',
            field=models.URLField(blank=True),
        ),
    ]
