# Generated by Django 3.1.7 on 2021-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapak', '0002_auto_20210324_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapakmodel',
            name='lapak_type',
            field=models.CharField(max_length=100),
        ),
    ]
