# Generated by Django 3.1.7 on 2021-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapak', '0003_auto_20210324_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lapakmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='lapakmodel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lapakmodel',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='lapakmodel',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lapakmodel',
            name='lapak_name',
            field=models.CharField(blank=True, default='Fulan', max_length=100),
        ),
    ]
