# Generated by Django 3.1.7 on 2021-03-30 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lapak', '0009_auto_20210330_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeLapakModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lapak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='lapak.lapakmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
