# Generated by Django 3.1.7 on 2021-03-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapak', '0010_likelapakmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likelapakmodel',
            old_name='lapak',
            new_name='lapak_id',
        ),
    ]
