# Generated by Django 3.1.7 on 2021-04-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapak', '0011_auto_20210330_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likelapakmodel',
            old_name='lapak_id',
            new_name='lapak',
        ),
    ]
