# Generated by Django 3.1.7 on 2021-04-04 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lapak', '0012_auto_20210404_0652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likelapakmodel',
            unique_together={('lapak', 'user')},
        ),
    ]
